package control;

public enum Options {
	
	SHIP_SELECTED,ADD_SHIP_VERTICAL,ADD_SHIP_HORIZONTAL,GET_BOAT,GET_VESSEL,GET_SUBMARINE,MISSILE_STATION, ADD_VERTICAL,ADD_HORIZONTAL,
	GET_AIRCRAFT_CARRIER,START_GAME, INSTRUCTIONS, START, EXIT, START_MATCH;
}