package protocols;

public enum Response {
	WAIT_GAME, START_GAME, HORIZONTAL_LEFT, HORIZONTAL_RIGHT, VERTICAL_BELOW,
	VERTICAL_ABOVE, NONE, ERROR, CENTER, START_MATCH, WARNING_MATCH, WAITING_MATCH	
}